typography_spectrum: 0.003413228318095207
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2705402923747897
  lightness: 0.5478613581508398
  saturation: 0.9670406975783408
  rhythmicContrast: 0.6144073265604675
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.33289247332140803
analytics:
  google: null
  facebook: null
  twitter: null
name: MAGIS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: magis
description: property management & more
purpose: []
